server :
    port : 8090

spring :
    datasource:
        url: jdbc:mysql://192.168.219.115:3306/talkingpotato?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        username: miewone
        password: tlqkfdk156
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true